<a href="https://colab.research.google.com/github/venkey024/Numpy_Assignment/blob/main/Assignment_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Import the numpy package under the name np (★☆☆)
(hint: import … as …)

In [ ]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)
(hint: np.__version__, np.show_config)

In [ ]:
print(np.__version__,np.show_config)

1.25.2 <function show at 0x7852599ec0d0>


3. Create a null vector of size 10

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


 4.How to find the memory size of any array (★☆☆)

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a.size)
print(a.itemsize)

6
8


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
a = np.arange(9)
b = a.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a = np.array([1,2,0,0,4,0])
b = np.argwhere(a == 0).flatten()
print(b)

[2 3 5]


Create a 3x3 identity matrix

In [ ]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
a = np.random.random((3,3,3))
print(a)

[[[0.28851464 0.43408447 0.99983773]
  [0.2511151  0.1779316  0.97894563]
  [0.22860382 0.41131463 0.62370581]]

 [[0.15452714 0.27193109 0.51908002]
  [0.50339565 0.28892087 0.4058096 ]
  [0.85921709 0.38664097 0.65929214]]

 [[0.5033666  0.59767492 0.94867863]
  [0.85451561 0.85826622 0.34390785]
  [0.69860989 0.49831324 0.18175747]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
a = np.random.random((10,10))
print(a)
print(np.max(a))
print(np.min(a))

[[0.84681436 0.92901716 0.32510105 0.89811773 0.58907856 0.40994373
  0.58542828 0.91736417 0.46164561 0.70023651]
 [0.15258869 0.46416425 0.7869838  0.04860853 0.6883883  0.56401147
  0.16926375 0.62703598 0.99509482 0.96551022]
 [0.93318523 0.15748564 0.66283503 0.51422899 0.6805727  0.46265625
  0.76962517 0.97707886 0.53884323 0.41243657]
 [0.53534661 0.17650175 0.44310098 0.35866506 0.73291126 0.38263458
  0.40296185 0.9381638  0.10930429 0.37381159]
 [0.72520304 0.83189347 0.80119518 0.20878983 0.93461414 0.63523427
  0.99028709 0.2443427  0.90600408 0.05192905]
 [0.94026403 0.84688233 0.32963629 0.95146113 0.81776453 0.91191613
  0.07548529 0.5552263  0.61552445 0.09018607]
 [0.85664832 0.75361176 0.72821181 0.63881798 0.6675903  0.0962943
  0.67698605 0.78551494 0.78581887 0.12467698]
 [0.3201848  0.08648433 0.13650461 0.53972065 0.22754428 0.45430922
  0.05122925 0.43030514 0.744266   0.12788388]
 [0.1940552  0.41395925 0.10896836 0.09535889 0.58317231 0.05822678
  0.85180146 

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
a = np.random.random(30)
print(a)
print(np.mean(a))

[0.73025352 0.15331868 0.06252748 0.53149303 0.03680143 0.68161396
 0.37486232 0.8766703  0.0986499  0.05060955 0.5841198  0.33507466
 0.26296344 0.64907572 0.23455217 0.69428026 0.75650601 0.57656553
 0.83284414 0.88114771 0.21940073 0.05895505 0.42131017 0.84335325
 0.57562978 0.71201353 0.76886854 0.85226731 0.26507361 0.44618796]
0.4855663185957605


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.ones([5,5])
a[1:-1:,1:-1:] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.random.random((3,2))
print(a)

[[0.47881231 0.34175523]
 [0.40928391 0.27479426]
 [0.20971659 0.043082  ]]


16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.array([[1,2],[3,4]])
print(np.pad(a,pad_width=1))

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


17. What is the result of the following expression? (★☆☆)
(hint: NaN = not a number, inf = infinity)

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
a = np.array([1,2,3,4])
print(np.diag(a,k=0))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
a = np.zeros((8,8))
a[0::2,0::2] = 1
a[1::2,1::2] = 1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
(hint: np.unravel_index)

In [ ]:

shape = (6,7,8)
a = np.unravel_index(99,shape)
print(a)

(1, 5, 3)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
a = np.array([[1,0],[0,1]])
til = np.tile(a,(4,4))
print(til)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


22. Normalize a 5x5 random matrix (★☆☆)
(hint: (x - min) / (max - min))

In [ ]:
matrix = np.eye(5)
min_val = a.min()
max_val = a.max()
normalized_matrix = (matrix - min_val) / (max_val - min_val)
print(normalized_matrix)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
(hint: np.dtype)

In [ ]:
import numpy as np

# Step 1: Define the custom dtype
color_dtype = np.dtype([
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8),
    ('a', np.uint8)
])

# Step 2: Create an example array using this dtype
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)

# Step 3: Print the array and its dtype
print("Colors array:\n", colors)
print("Dtype:", colors.dtype)

Colors array:
 [(2,   1,   0, 255) (0, 255,   0, 255) (0,   0, 255, 255)]
Dtype: [('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
(hint: np.dot | @)

In [ ]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
a@b

array([[0.15767459, 0.38677136],
       [0.47410085, 0.66013667],
       [0.13797406, 0.4674299 ],
       [0.81286306, 0.66889851],
       [0.96687456, 0.85913976]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
(hint: >, <=)

In [ ]:
a = np.array([1,5,6,7,87,6,43])
a[(a>3) & (a<8)] = a[(a>3) & (a<8)] *0
print(a)

[ 1  0  0  0 87  0 43]


26. What is the output of the following script? (★☆☆)
(hint: np.sum)

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [ ]:
z = np.array([4])
print(z*z)
print(2<<z>>2)
print(z<-2)
print(1j *z)
print(z/1/1)
print(z<z>z)

[16]
[8]
[False]
[0.+4.j]
[4.]
[False]


28. What are the result of the following expressions?

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)

In [ ]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
np.array([np.nan]).astype(int).astype(float)

nan
0


<ipython-input-56-52e5be358f56>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))
<ipython-input-56-52e5be358f56>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))
<ipython-input-56-52e5be358f56>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

29. How to round away from zero a float array ? (★☆☆)
(hint: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
arr = np.random.uniform(10,size =10)
print(arr)
rounded_arr =np.ceil(np.abs(arr))
print(rounded_arr)


[1.25296178 5.57999965 1.21294813 7.07205251 9.25007108 7.17295016
 3.77773663 1.44137269 5.40307428 2.63910119]
[ 2.  6.  2.  8. 10.  8.  4.  2.  6.  3.]


30. How to find common values between two arrays? (★☆☆)
(hint: np.intersect1d)

In [ ]:
a = np.random.randint(10,size=10)
print(a)
b = np.random.randint(10,size=10)
print(b)
c = np.intersect1d(a,b)
print("The common eleemnts : ",c)

[5 4 7 3 0 2 7 6 6 1]
[4 6 6 8 0 9 4 5 5 5]
The common eleemnts :  [0 4 5 6]


31. How to ignore all numpy warnings (not recommended)? (★☆☆)
(hint: np.seterr, np.errstate)

In [ ]:
# Ignore all warnings
np.seterr(all='ignore')

# Example code that would normally raise warnings
a = np.array([1.0, 2.0, np.nan])
b = np.array([0.0, 0.0, 0.0])
c = a / b
print(c)

with np.errstate(all='ignore'):
  d = a/b

print(d)

[inf inf nan]
[inf inf nan]


32. Is the following expressions true? (★☆☆)
(hint: imaginary number)

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

(hint: np.datetime64, np.timedelta64)

In [ ]:
today = np.datetime64('today')
print("Today date",today)

# yesterday
yesterday = today - np.timedelta64(1,'D')

print("yesterady date",yesterday)


#tomorrow
tomorrow = today + np.timedelta64(1,'D')
print("Tommorrow date is ",tomorrow)

Today date 2024-06-29
yesterady date 2024-06-28
Tommorrow date is  2024-06-30


34. How to get all the dates corresponding to the month of July 2016? (★★☆)
(hint: np.arange(dtype=datetime64['D']))bold text

In [ ]:
np.arange('2016-07-01','2016-07-30',dtype = 'datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29'], dtype='datetime64[D]')

35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
(hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
import numpy as np

# Example arrays
A = np.array([1.0, 2.0, 3.0])
B = np.array([4.0, 5.0, 6.0])

# Step 1: A + B
np.add(A, B, out=A)  # A now becomes A + B

# Step 2: -A
np.negative(A, out=A)  # A now becomes -(A + B)

# Step 3: -A / 2
np.divide(A, 2, out=A)  # A now becomes -(A + B) / 2

# Step 4: (A + B) * (-A / 2)
np.multiply(A, A, out=A)  # A now becomes (A + B) * (-(A + B) / 2)

# Print the result
print(A)

[ 6.25 12.25 20.25]


36. Extract the integer part of a random array using 5 different methods (★★☆)

(hint: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
a = np.random.randn(10)
a = a - np.mod(a,1)
print(a)
print(np.floor(a))
print(np.ceil(a))
print(a.astype(int))
print(np.trunc(a))



[ 0. -1.  0.  0.  0.  0. -1.  0.  0. -1.]
[ 0. -1.  0.  0.  0.  0. -1.  0.  0. -1.]
[ 0. -1.  0.  0.  0.  0. -1.  0.  0. -1.]
[ 0 -1  0  0  0  0 -1  0  0 -1]
[ 0. -1.  0.  0.  0.  0. -1.  0.  0. -1.]


In [ ]:
a = np.random.randn(10)
a = a - np.mod(a,1)
print(a)

[-1. -1.  0.  0.  1. -2. -1.  0. -1. -2.]


37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
(hint: np.arange)

In [ ]:

# a = np.arange(0,5)
# b = a[:,np.newaxis]
# print(b)


a = np.tile(np.arange(0,4),(5,1))
print(a)





[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
(hint: np.fromiter)

In [ ]:

# Define a generator function that generates 10 integers
def generate_integers():
    for i in range(10):
        yield i

# Use np.fromiter to build an array from the generator
array = np.fromiter(generate_integers(), dtype=int, count=10)

print(array)

[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
(hint: np.linspace)

In [ ]:
a = np.linspace(0.1,0.9,10)
print(a)

[0.1        0.18888889 0.27777778 0.36666667 0.45555556 0.54444444
 0.63333333 0.72222222 0.81111111 0.9       ]


40. Create a random vector of size 10 and sort it (★★☆)
(hint: sort)

In [ ]:
a = np.random.randint(0,11,size =10)
print(a)

print(np.sort(a))

[8 1 9 6 9 8 8 1 6 3]
[1 1 3 6 6 8 8 8 9 9]


41. How to sum a small array faster than np.sum? (★★☆)
(hint: np.add.reduce)

In [ ]:
from timeit import default_timer as timer
a = np.random.randn(1000)
b = np.random.randn(1000)
# print(a)
# print(b)
A = list(a)
B = list(b)
T = 1000
def sum_ar():
  s1 = 0
  for i in range(len(A)):
    s1 += a
  return s1
def sum_red():
  return np.add.reduce(B)

# calculate the timing
start = timer()
for t in range(T):
  sum_ar()
end = timer()
t1 = end - start

# for dot2
start = timer()
for t in range(T):
  sum_red()
end = timer()
t2 = end - start

print('time with sum_ar',t1)
print('time with sum_redUced array',t2)

print("ratio",t1/t2)

time with sum_ar 1.0882547470000645
time with sum_redUced array 0.10594458800005668
ratio 10.271923913654582


42. Consider two random array A and B, check if they are equal (★★☆)
(hint: np.allclose, np.array_equal)

In [ ]:
a = np.array([3,4,5,7,8,9])
b = np.array([5,6,7,8,9,0])
np.allclose(a,b)
print(np.array_equal(a,b))

False


43. Make an array immutable (read-only) (★★☆)
(hint: flags.writeable)

In [ ]:
a = np.array([1,2,3,4])
a.flags.writeable = False

try:
    a[0] = 10
except ValueError as e:
  print("Error:", e)


Error: assignment destination is read-only


44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
(hint: np.sqrt, np.arctan2)

In [ ]:
# Create a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.rand(10, 2)

# Extract x and y coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

# Compute the radius (r) and angle (theta)
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

# Combine r and theta into a single matrix representing polar coordinates
polar_coords = np.column_stack((r, theta))

print("Cartesian coordinates:")
print(cartesian_coords)
print("\nPolar coordinates:")
print(polar_coords)

Cartesian coordinates:
[[0.76329536 0.71236361]
 [0.24525014 0.40737685]
 [0.16289015 0.36161373]
 [0.74669278 0.97021036]
 [0.44667939 0.12946392]
 [0.32681422 0.80630341]
 [0.70806731 0.40882267]
 [0.07027404 0.92456348]
 [0.86485827 0.45683634]
 [0.93545911 0.86670395]]

Polar coordinates:
[[1.04406979 0.75089728]
 [0.47550344 1.02889083]
 [0.39660773 1.14756538]
 [1.22427866 0.91485655]
 [0.46506277 0.28210644]
 [0.87001881 1.18570863]
 [0.81761562 0.52361977]
 [0.92723033 1.49493439]
 [0.97809982 0.48596873]
 [1.27524879 0.74726519]]


45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
(hint: argmax)

In [ ]:
a = np.random.randint(10,size =10)
print(a)
cond = np.max(a)
print(f"The maximum element is {cond}")
b = np.argmax(a).flatten()
a[b]= 0
print(a)

[7 2 7 5 7 2 9 0 8 8]
The maximum element is 9
[7 2 7 5 7 2 0 0 8 8]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
(hint: np.meshgrid)

In [ ]:
import numpy as np

# Define the grid size
grid_size = 5

# Generate a grid of x and y coordinates
x, y = np.meshgrid(np.linspace(0, 1, grid_size), np.linspace(0, 1, grid_size))

# Create a structured array with fields 'x' and 'y'
structured_array = np.zeros((grid_size, grid_size), dtype=[('x', 'f4'), ('y', 'f4')])

# Assign the x and y coordinates to the structured array
structured_array['x'], structured_array['y'] = x, y

print(structured_array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
(hint: np.subtract.outer)

In [ ]:
# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix C
C = 1.0 / np.subtract.outer(X, Y)

print("X:", X)
print("Y:", Y)
print("Cauchy matrix C:\n", C)

X: [1 2 3]
Y: [4 5 6]
Cauchy matrix C:
 [[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
(hint: np.iinfo, np.finfo, eps)

In [ ]:
integer_types = [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64]

print("Integer types:")
for dtype in integer_types:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: min={info.min}, max={info.max}")

# Floating-point types
floating_types = [np.float16, np.float32, np.float64]

print("\nFloating-point types:")
for dtype in floating_types:
    info = np.finfo(dtype)
    print(f"{dtype.__name__}: min={info.min}, max={info.max}, eps={info.eps}")

Integer types:
int8: min=-128, max=127
int16: min=-32768, max=32767
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=9223372036854775807
uint8: min=0, max=255
uint16: min=0, max=65535
uint32: min=0, max=4294967295
uint64: min=0, max=18446744073709551615

Floating-point types:
float16: min=-65504.0, max=65504.0, eps=0.0009765625
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38, eps=1.1920928955078125e-07
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308, eps=2.220446049250313e-16


49. How to print all the values of an array? (★★☆)
(hint: np.set_printoptions)

In [ ]:
large_array = np.arange(100)

# Set print options to print all elements
np.set_printoptions(threshold=np.inf)

# Print the array
print(large_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


50. How to find the closest value (to a given scalar) in a vector? (★★☆)
(hint: argmin)

In [ ]:
vector = np.array([1.2, 3.5, 2.1, 7.8, 5.4])

# Given scalar
scalar = 4.0

# Find index of closest value
index = np.argmin(np.abs(vector - scalar))

# Closest value
closest_value = vector[index]

print(f"Vector: {vector}")
print(f"Scalar: {scalar}")
print(f"Closest value: {closest_value} at index {index}")

Vector: [1.2 3.5 2.1 7.8 5.4]
Scalar: 4.0
Closest value: 3.5 at index 1
